spring:
  application:
    name: "ServiceBookingSystem"
  datasource:
    url: "jdbc:mysql://localhost:3306/service_booking_system_db"
    username: root
    password: Abhi@7239
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true